# Generated by Django 4.1.2 on 2022-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CandidateName", models.CharField(max_length=200)),
                (
                    "CandidateDescription",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "CandidateImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="CandidateImage"
                    ),
                ),
                (
                    "CandidateProgram",
                    models.FileField(
                        blank=True, null=True, upload_to="CandidateProgram"
                    ),
                ),
            ],
        ),
    ]
