# Generated by Django 4.1.2 on 2022-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CandidateName", models.CharField(max_length=200)),
                ("CandidateDescription", models.CharField(max_length=200)),
                ("CandidateImage", models.ImageField(upload_to="images")),
                ("CandidateProgram", models.FileField(upload_to="")),
            ],
        ),
    ]
