# Generated by Django 4.1.2 on 2022-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="id",),
        migrations.AlterField(
            model_name="candidate",
            name="CandidateName",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
