# Generated by Django 4.1.2 on 2022-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="CandidateDescription",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="CandidateImage",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="CandidateProgram",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
