# Generated by Django 4.1.2 on 2022-11-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0002_remove_candidate_id_alter_candidate_candidatename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ElectionName", models.CharField(max_length=200)),
                (
                    "ElectionStatus",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ElectionApiKey",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
