# Generated by Django 4.1.2 on 2022-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0003_election"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="ElectionApiKey",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
