# Generated by Django 4.1.2 on 2022-11-08 15:51

import AdminSpace.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0003_alter_candidate_candidateimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="CandidateImage",
            field=AdminSpace.models.ImageField(blank=True, upload_to="CandidateImage"),
        ),
    ]
