# Generated by Django 4.1.2 on 2022-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0005_election_electioncandidate"),
    ]

    operations = [
        migrations.RemoveField(model_name="election", name="ElectionCandidate",),
        migrations.AddField(
            model_name="election",
            name="ElectionCandidates",
            field=models.ManyToManyField(to="AdminSpace.candidate"),
        ),
    ]
