# Generated by Django 4.1.2 on 2022-11-23 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0006_remove_election_electioncandidate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="election", name="ElectionCandidates",),
        migrations.AddField(
            model_name="election",
            name="ElectionCandidates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
