# Generated by Django 4.1.2 on 2022-11-23 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0007_remove_election_electioncandidates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="ElectionCandidates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
