# Generated by Django 4.1.2 on 2022-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSpace", "0010_alter_election_electioncandidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="ElectionEndDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="ElectionStartDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
