# Generated by Django 4.1.2 on 2023-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartVoteLite", "0002_alter_electionlite_electioncode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionlite",
            name="ElectionCode",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
