# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: dev CI/CD

on:
  push:
    branches:
      - 'B/Features#**'
      - 'B/Bug#**'
      - 'B/Modification#**'
  pull_request:
    branches:
      - master
      - main
      - 'BlockChain'

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: position to Blockchain project
        run: cd Blockchain
      - name: unit tests
        run: ./mvnw -B clean test
      - name: integration tests
        if: github.event.pull_request.base.ref == 'main'
        run: ./mvnw -B clean integration-test